display_name: lsFusion client
icon: web/icons/Icon-192.png
summary: lsFusion client
license: MIT
vendor: lsFusion
group: Applications/Productivity
categories:
  - Office
  - Utility
requires:
  - gtk3
  - mesa-libGL
  - mesa-libEGL
  - mesa-libGLES
  - mesa-libgbm
  - mesa-dri-drivers
  - webkit2gtk4.1
  - libappindicator-gtk3
  - xz-libs
  - libstdc++
  - mesa-libGLU
  - libX11
  - libXcursor
  - libXinerama
  - libXrandr
  - libXi
  - libXrender
  - libXfixes
  - libXtst
  - nss
  - nspr
  - alsa-lib
  - libserialport
  - cups-libs
