display_name: lsFusion Flutter client
icon: web/icons/Icon-192.png
summary: lsFusion Flutter client
license: MIT
vendor: lsFusion
group: Applications/Productivity
categories:
  - Office
  - Utility
requires:
  - gtk3
  - libappindicator-gtk3
  - xz-libs
  - libstdc++
  - mesa-libGLU
  - libX11
  - nss
  - nspr
  - alsa-lib
