app_info:
  id: com.lsfusion.flutterclient
  name: lsFusion Flutter client
  icon: web/icons/Icon-192.png
  version: 1.0.0
  exec: flutter_client

include: []
exclude: []
# AppImage configuration
# More options can be added here if needed
