display_name: lsFusion Flutter client
package_name: flutter-client
maintainer:
  name: lsFusion
  email: support@lsfusion.org
installed_size: 25000
priority: optional
section: utils
categories:
  - Office
  - Utility
dependencies:
  - libgtk-3-0
  - libappindicator3-1
  - liblzma5
