display_name: lsFusion
package_name: lsfusion-client
icon: web/icons/Icon-192.png
maintainer:
  name: lsFusion
  email: support@lsfusion.org
installed_size: 25000
priority: optional
section: utils
categories:
  - Office
  - Utility
dependencies:
  - libgtk-3-0
  - libappindicator3-1
  - liblzma5
  - libwpewebkit-1.0-3
  - libwpebackend-fdo-1.0-1
  - libwpe-1.0-1
  - libsecret-1-0
  - libepoxy0
