name: Build All Platforms
on:
#  push:
#    branches: [ main ]
#  pull_request:
  workflow_dispatch:

jobs:
  linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit

  windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit

#  macos:
#    uses: ./.github/workflows/macos.yml
#    secrets: inherit

  android:
    uses: ./.github/workflows/android.yml
    secrets: inherit

#  ios:
#    uses: ./.github/workflows/ios.yml
#    secrets: inherit